# To view the documentation locally on your machine, use the following steps
#
# Clone the GitHub cppfront repo locally, then on the command line:
#
#   cd /github/cppfront
#   python -m venv venv
#   source venv/bin/activate
#   pip install mkdocs-material
#   mkdocs new .
#   mkdocs serve
#
# The last command should eventually print something like
#   Serving on http://127.0.0.1:8000/
# and you can open that URL in a local brower. If you are locally editing
# the documentation, leave the server process running and the browser
# pages will auto-reload as you save edits.
#
site_name: "Cpp2 and cppfront — An experimental 'C++ syntax 2', and its first compiler"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.footnote.tooltips
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: switch to light mode
        primary: teal
        accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy <a href="https://github.com/hsutter" target="_blank" rel="noopener">Herb Sutter</a> &bull; <a href="https://github.com/hsutter/cppfront/blob/main/LICENSE">cppfront license </a>
